language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - composer install

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
